package david_diaz_lab6;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_LogIn = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_User = new javax.swing.JTextField();
        jTF_Password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jD_Crear_Cliente = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTF_Nombre = new javax.swing.JTextField();
        jTF_Edad = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jD_Eliminar_Cliente = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jCB_Cliente = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jD_Crear_Producto = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTF_Nombre_Producto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTF_Categoria = new javax.swing.JTextField();
        Guardar1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTF_Precio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTF_Descuento = new javax.swing.JTextField();
        jD_Modificar_Producto = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTF_Nombre_Producto1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTF_Categoria1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTF_Precio1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTF_Descuento1 = new javax.swing.JTextField();
        Guardar2 = new javax.swing.JButton();
        jCB_Producto = new javax.swing.JComboBox<>();
        jD_Eliminar_Producto = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jCB_Producto1 = new javax.swing.JComboBox<>();
        Guardar3 = new javax.swing.JButton();
        jD_Compra = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jCB_Compra_Cliente = new javax.swing.JComboBox<>();
        jCB_Compra_Producto = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_Factura = new javax.swing.JTextArea();
        jD_Inventario = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Inventario = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_Inventario1 = new javax.swing.JTable();
        jD_Ganancia = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jTF_Ganancia = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Administrador");

        jLabel2.setText("User:");

        jLabel3.setText("Password:");

        jButton1.setText("LogIn");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jD_LogInLayout = new javax.swing.GroupLayout(jD_LogIn.getContentPane());
        jD_LogIn.getContentPane().setLayout(jD_LogInLayout);
        jD_LogInLayout.setHorizontalGroup(
            jD_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_LogInLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jD_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jD_LogInLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_Password))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jD_LogInLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jTF_User))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jD_LogInLayout.setVerticalGroup(
            jD_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_LogInLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jD_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Crear Cliente");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Edad:");

        Guardar.setText("Guardar");
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jD_Crear_ClienteLayout = new javax.swing.GroupLayout(jD_Crear_Cliente.getContentPane());
        jD_Crear_Cliente.getContentPane().setLayout(jD_Crear_ClienteLayout);
        jD_Crear_ClienteLayout.setHorizontalGroup(
            jD_Crear_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Crear_ClienteLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jD_Crear_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jD_Crear_ClienteLayout.createSequentialGroup()
                        .addGroup(jD_Crear_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jD_Crear_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Edad)
                            .addComponent(jTF_Nombre)))
                    .addComponent(Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jD_Crear_ClienteLayout.setVerticalGroup(
            jD_Crear_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Crear_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jD_Crear_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_Crear_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTF_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Cliente:");

        jButton2.setText("Eliminar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jD_Eliminar_ClienteLayout = new javax.swing.GroupLayout(jD_Eliminar_Cliente.getContentPane());
        jD_Eliminar_Cliente.getContentPane().setLayout(jD_Eliminar_ClienteLayout);
        jD_Eliminar_ClienteLayout.setHorizontalGroup(
            jD_Eliminar_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Eliminar_ClienteLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jD_Eliminar_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jD_Eliminar_ClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jD_Eliminar_ClienteLayout.setVerticalGroup(
            jD_Eliminar_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Eliminar_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jD_Eliminar_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCB_Cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Crear Producto");

        jLabel9.setText("Nombre:");

        jLabel10.setText("Categoria:");

        Guardar1.setText("Guardar");
        Guardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Guardar1MouseClicked(evt);
            }
        });

        jLabel11.setText("Precio:");

        jLabel12.setText("Descuento:");

        javax.swing.GroupLayout jD_Crear_ProductoLayout = new javax.swing.GroupLayout(jD_Crear_Producto.getContentPane());
        jD_Crear_Producto.getContentPane().setLayout(jD_Crear_ProductoLayout);
        jD_Crear_ProductoLayout.setHorizontalGroup(
            jD_Crear_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Crear_ProductoLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jD_Crear_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Guardar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jD_Crear_ProductoLayout.createSequentialGroup()
                        .addGroup(jD_Crear_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jD_Crear_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Categoria)
                            .addComponent(jTF_Nombre_Producto)
                            .addGroup(jD_Crear_ProductoLayout.createSequentialGroup()
                                .addGroup(jD_Crear_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jD_Crear_ProductoLayout.setVerticalGroup(
            jD_Crear_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Crear_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jD_Crear_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTF_Nombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_Crear_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTF_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_Crear_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTF_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_Crear_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTF_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Modificar Producto");

        jLabel14.setText("Nombre:");

        jLabel15.setText("Categoria:");

        jLabel16.setText("Precio:");

        jLabel17.setText("Descuento:");

        Guardar2.setText("Guardar");
        Guardar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Guardar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jD_Modificar_ProductoLayout = new javax.swing.GroupLayout(jD_Modificar_Producto.getContentPane());
        jD_Modificar_Producto.getContentPane().setLayout(jD_Modificar_ProductoLayout);
        jD_Modificar_ProductoLayout.setHorizontalGroup(
            jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Modificar_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Guardar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jD_Modificar_ProductoLayout.createSequentialGroup()
                            .addGroup(jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTF_Categoria1)
                                .addComponent(jTF_Nombre_Producto1)
                                .addGroup(jD_Modificar_ProductoLayout.createSequentialGroup()
                                    .addGroup(jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTF_Precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTF_Descuento1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 92, Short.MAX_VALUE)))))
                    .addGroup(jD_Modificar_ProductoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jD_Modificar_ProductoLayout.setVerticalGroup(
            jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Modificar_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jD_Modificar_ProductoLayout.createSequentialGroup()
                        .addComponent(jCB_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTF_Nombre_Producto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jTF_Categoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTF_Precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_Modificar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTF_Descuento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Eliminar Producto");

        Guardar3.setText("Guardar");
        Guardar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Guardar3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jD_Eliminar_ProductoLayout = new javax.swing.GroupLayout(jD_Eliminar_Producto.getContentPane());
        jD_Eliminar_Producto.getContentPane().setLayout(jD_Eliminar_ProductoLayout);
        jD_Eliminar_ProductoLayout.setHorizontalGroup(
            jD_Eliminar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Eliminar_ProductoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Guardar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
            .addGroup(jD_Eliminar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jD_Eliminar_ProductoLayout.createSequentialGroup()
                    .addContainerGap(46, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCB_Producto1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)))
        );
        jD_Eliminar_ProductoLayout.setVerticalGroup(
            jD_Eliminar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_Eliminar_ProductoLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(Guardar3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jD_Eliminar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jD_Eliminar_ProductoLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(jD_Eliminar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jD_Eliminar_ProductoLayout.createSequentialGroup()
                            .addComponent(jCB_Producto1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addGap(1, 1, 1))
                        .addComponent(jLabel18))
                    .addGap(242, 242, 242)))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Compra");

        jLabel20.setText("Cliente:");

        jLabel21.setText("Producto:");

        jButton3.setText("Compra");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jTA_Factura.setEditable(false);
        jTA_Factura.setColumns(20);
        jTA_Factura.setRows(5);
        jScrollPane2.setViewportView(jTA_Factura);

        javax.swing.GroupLayout jD_CompraLayout = new javax.swing.GroupLayout(jD_Compra.getContentPane());
        jD_Compra.getContentPane().setLayout(jD_CompraLayout);
        jD_CompraLayout.setHorizontalGroup(
            jD_CompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_CompraLayout.createSequentialGroup()
                .addGroup(jD_CompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jD_CompraLayout.createSequentialGroup()
                        .addGroup(jD_CompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jD_CompraLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_CompraLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jD_CompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jD_CompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCB_Compra_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCB_Compra_Producto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_CompraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jD_CompraLayout.setVerticalGroup(
            jD_CompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_CompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(27, 27, 27)
                .addGroup(jD_CompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jD_CompraLayout.createSequentialGroup()
                        .addGroup(jD_CompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jCB_Compra_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jD_CompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jCB_Compra_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Inventario");

        jT_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoria", "Precio", "Descuento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jT_Inventario);

        jButton4.setText("Cargar Archivo");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Guardar Archivo");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jT_Inventario1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoria", "Precio", "Descuento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jT_Inventario1);

        javax.swing.GroupLayout jD_InventarioLayout = new javax.swing.GroupLayout(jD_Inventario.getContentPane());
        jD_Inventario.getContentPane().setLayout(jD_InventarioLayout);
        jD_InventarioLayout.setHorizontalGroup(
            jD_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_InventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jD_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jD_InventarioLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jD_InventarioLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jD_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jD_InventarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jD_InventarioLayout.setVerticalGroup(
            jD_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_InventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(96, 96, 96)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jD_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(jD_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jD_InventarioLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("Ganancia:");

        jTF_Ganancia.setEditable(false);

        javax.swing.GroupLayout jD_GananciaLayout = new javax.swing.GroupLayout(jD_Ganancia.getContentPane());
        jD_Ganancia.getContentPane().setLayout(jD_GananciaLayout);
        jD_GananciaLayout.setHorizontalGroup(
            jD_GananciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_GananciaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jD_GananciaLayout.setVerticalGroup(
            jD_GananciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_GananciaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jD_GananciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jTF_Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Administrador");

        jMenuItem1.setText("LogIn");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Crear Cliente");
        jMenuItem2.setEnabled(false);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Eliminar Cliente");
        jMenuItem5.setEnabled(false);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenu3.setText("Producto");
        jMenu3.setEnabled(false);

        jMenuItem3.setText("Crear Producto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem6.setText("Modificar Producto");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Eliminar Producto");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenu1.add(jMenu3);

        jMenuItem10.setText("Inventario");
        jMenuItem10.setEnabled(false);
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setText("Ganancia");
        jMenuItem11.setEnabled(false);
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem4.setText("LogOut");
        jMenuItem4.setEnabled(false);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");

        jMenuItem8.setText("Comprar Producto");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       jD_LogIn.setModal(true);
       jD_LogIn.pack();
       jD_LogIn.setLocationRelativeTo(this);
       jD_LogIn.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jTF_User.getText().equals(user) && jTF_Password.getText().equals(pass)) {
            jMenuItem1.setEnabled(false);
            jMenuItem2.setEnabled(true);
            jMenuItem4.setEnabled(true);
            jMenuItem5.setEnabled(true);
            jMenuItem10.setEnabled(true);
            jMenuItem11.setEnabled(true);
            jMenu3.setEnabled(true);
            JOptionPane.showMessageDialog(jD_LogIn, "Usuario Ingresado");
            jD_LogIn.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(jD_LogIn, "Error de Usuario");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
            jMenuItem1.setEnabled(true);
            jMenuItem2.setEnabled(false);
            jMenuItem4.setEnabled(false);
            jMenuItem5.setEnabled(false);
            jMenuItem10.setEnabled(false);
            jMenuItem11.setEnabled(false);
            jMenu3.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Se ha Cerrado sesión");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jD_Modificar_Producto.setModal(true);
        jD_Modificar_Producto.pack();
        jD_Modificar_Producto.setLocationRelativeTo(this);
        jD_Modificar_Producto.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseClicked
        Cliente c = new Cliente(jTF_Nombre.getText(), Integer.parseInt(jTF_Edad.getText()));
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)jCB_Cliente.getModel();
        modelo.addElement(c);
        jCB_Cliente.setModel(modelo);
        jCB_Compra_Cliente.setModel(modelo);
        JOptionPane.showMessageDialog(jD_Eliminar_Cliente, "Cliente Creado");
        jTF_Nombre.setText("");
        jTF_Edad.setText("");
    }//GEN-LAST:event_GuardarMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)jCB_Cliente.getModel();
        modelo.removeElementAt(jCB_Cliente.getSelectedIndex());
        jCB_Cliente.setModel(modelo);
        jCB_Compra_Cliente.setModel(modelo);
        JOptionPane.showMessageDialog(jD_Eliminar_Cliente, "Cliente Eliminado");
    }//GEN-LAST:event_jButton2MouseClicked

    private void Guardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guardar1MouseClicked
        Producto p =new Producto(jTF_Nombre_Producto.getText(), jTF_Categoria.getText(), Double.parseDouble(jTF_Precio.getText()), Double.parseDouble(jTF_Descuento.getText()));
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)jCB_Producto.getModel();
        modelo.addElement(p);
        jCB_Producto.setModel(modelo);
        jCB_Producto1.setModel(modelo);
        jCB_Compra_Producto.setModel(modelo);
        JOptionPane.showMessageDialog(jD_Crear_Producto, "Producto Creado");
        jTF_Nombre_Producto.setText("");
        jTF_Categoria.setText("");
        jTF_Precio.setText("");
        jTF_Descuento.setText("");
    }//GEN-LAST:event_Guardar1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jD_Crear_Producto.setModal(true);
        jD_Crear_Producto.pack();
        jD_Crear_Producto.setLocationRelativeTo(this);
        jD_Crear_Producto.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void Guardar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guardar2MouseClicked
        String nombre = "", categoria = "";
        double precio = 0, descuento = 0;
        int toc = 0, toc_d = 0;
        nombre = jTF_Nombre_Producto1.getText();
        categoria = jTF_Categoria1.getText();
        precio = Double.parseDouble(jTF_Precio1.getText());
        descuento = Double.parseDouble(jTF_Descuento1.getText());
        if (jTF_Precio1.getText().equals("")) {
            toc = 1;
        }
        if (jTF_Descuento1.getText().equals("")) {
            toc_d = 1;
        }
        if (jTF_Nombre_Producto1.getText().equals("")) {
            nombre = ((Producto)jCB_Producto.getModel()).getNombre();
        }
        if (jTF_Categoria1.getText().equals("")) {
            categoria = ((Producto)jCB_Producto.getModel()).getCategoria();
        }
        if (toc == 1) {
            precio = ((Producto)jCB_Producto.getModel()).getPrecio();
            toc = 0;
        }
        if (toc_d == 1) {
            descuento = ((Producto)jCB_Producto.getModel()).getDescuento();
            toc_d = 0;
        }
        Producto p =new Producto(nombre, categoria, precio, descuento);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)jCB_Producto.getModel();
        modelo.removeElementAt(jCB_Producto.getSelectedIndex());
        modelo.addElement(p);
        jCB_Producto.setModel(modelo);
        jCB_Producto1.setModel(modelo);
        jCB_Compra_Producto.setModel(modelo);
        JOptionPane.showMessageDialog(jD_Crear_Producto, "Producto Modificado");
        jTF_Nombre_Producto1.setText("");
        jTF_Categoria1.setText("");
        jTF_Precio1.setText("");
        jTF_Descuento1.setText("");
    }//GEN-LAST:event_Guardar2MouseClicked

    private void Guardar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guardar3MouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)jCB_Producto1.getModel();
        modelo.removeElementAt(jCB_Producto1.getSelectedIndex());
        jCB_Producto.setModel(modelo);
        jCB_Producto1.setModel(modelo);
        jCB_Compra_Producto.setModel(modelo);
        JOptionPane.showMessageDialog(jD_Eliminar_Producto, "Producto Eliminado");
    }//GEN-LAST:event_Guardar3MouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jD_Eliminar_Producto.setModal(true);
        jD_Eliminar_Producto.pack();
        jD_Eliminar_Producto.setLocationRelativeTo(this);
        jD_Eliminar_Producto.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String factura = "";
        ((Cliente)jCB_Compra_Cliente.getModel().getSelectedItem()).getProductos().add((Producto)jCB_Compra_Producto.getModel().getSelectedItem());
        
        descuento = ((Producto)jCB_Compra_Producto.getModel().getSelectedItem()).getPrecio() * ((Producto)jCB_Compra_Producto.getModel().getSelectedItem()).getDescuento();
        total_precio = ((Producto)jCB_Compra_Producto.getModel().getSelectedItem()).getPrecio() - descuento;
        ganancias += total_precio;
        JOptionPane.showMessageDialog(jD_Compra, "Compra Exitosa");
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)jCB_Compra_Producto.getModel();
        modelo.removeElementAt(jCB_Compra_Producto.getSelectedIndex());
        jCB_Compra_Producto.setModel(modelo);
        jCB_Producto.setModel(modelo);
        jCB_Producto1.setModel(modelo);
        jTA_Factura.setText("");
        factura = "Cliente: " + ((Cliente)jCB_Compra_Cliente.getModel().getSelectedItem()).getNombre() +"\n"
                + "Edad: " + ((Cliente)jCB_Compra_Cliente.getModel().getSelectedItem()).getEdad() + "\n";
        for (int i = 0; i < ((Cliente)jCB_Compra_Cliente.getModel().getSelectedItem()).getProductos().size() ; i++) {
            factura += "Productos\n" + ((Cliente)jCB_Compra_Cliente.getModel().getSelectedItem()).getProductos().get(i).getNombre() + "\n"
                    + "Precio: " + ((Cliente)jCB_Compra_Cliente.getModel().getSelectedItem()).getProductos().get(i).getPrecio() + "\n"
                    + "Categoria: " + ((Cliente)jCB_Compra_Cliente.getModel().getSelectedItem()).getProductos().get(i).getCategoria() + "\n"
                    + "Descuento: " + ((Cliente)jCB_Compra_Cliente.getModel().getSelectedItem()).getProductos().get(i).getDescuento();
        }
        jTA_Factura.setText(factura);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jD_Crear_Cliente.setModal(true);
        jD_Crear_Cliente.pack();
        jD_Crear_Cliente.setLocationRelativeTo(this);
        jD_Crear_Cliente.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jD_Eliminar_Cliente.setModal(true);
        jD_Eliminar_Cliente.pack();
        jD_Eliminar_Cliente.setLocationRelativeTo(this);
        jD_Eliminar_Cliente.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jD_Compra.setModal(true);
        jD_Compra.pack();
        jD_Compra.setLocationRelativeTo(this);
        jD_Compra.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        jD_Inventario.setModal(true);
        jD_Inventario.pack();
        jD_Inventario.setLocationRelativeTo(this);
        jD_Inventario.setVisible(true);
        DefaultTableModel modelo = (DefaultTableModel) jT_Inventario.getModel();
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        jT_Inventario.setModel(modelo);
        for (int i = 0; i < jCB_Compra_Producto.getModel().getSize(); i++) {
            Producto p = (Producto) jCB_Compra_Producto.getItemAt(i);
            Object[] row = {
                p.getNombre(),
                p.getCategoria(),
                p.getPrecio(),
                p.getDescuento()
            };
            modelo.addRow(row);
            jT_Inventario.setModel(modelo);
        }
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
       for (int i = 0; i < jCB_Compra_Producto.getModel().getSize(); i++) {
            Producto p = (Producto) jCB_Compra_Producto.getItemAt(i);
            AdministrarProducto ap = new AdministrarProducto("./salida.txt");
            ap.CargarArchivo();
            ap.getProductos().add(p);
           try {
               ap.EscribirArchivo();
           } catch (IOException ex) {
           }
       }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        DefaultTableModel modelo = (DefaultTableModel) jT_Inventario.getModel();
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        jT_Inventario.setModel(modelo);
        AdministrarProducto ap = new AdministrarProducto("./salida.txt");
        ap.CargarArchivo();
        for (int i = 0; i < ap.getProductos().size(); i++) {
            Producto p = ap.getProductos().get(i);
            Object[] row = {
                p.getNombre(),
                p.getCategoria(),
                p.getPrecio(),
                p.getDescuento()
            };
            modelo.addRow(row);
            jT_Inventario1.setModel(modelo);
        }
        try {
            ap.EscribirArchivo();
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jTF_Ganancia.setText("" + ganancias);
        jD_Ganancia.setModal(true);
        jD_Ganancia.pack();
        jD_Ganancia.setLocationRelativeTo(this);
        jD_Ganancia.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar1;
    private javax.swing.JButton Guardar2;
    private javax.swing.JButton Guardar3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jCB_Cliente;
    private javax.swing.JComboBox<String> jCB_Compra_Cliente;
    private javax.swing.JComboBox<Producto> jCB_Compra_Producto;
    private javax.swing.JComboBox<String> jCB_Producto;
    private javax.swing.JComboBox<String> jCB_Producto1;
    private javax.swing.JDialog jD_Compra;
    private javax.swing.JDialog jD_Crear_Cliente;
    private javax.swing.JDialog jD_Crear_Producto;
    private javax.swing.JDialog jD_Eliminar_Cliente;
    private javax.swing.JDialog jD_Eliminar_Producto;
    private javax.swing.JDialog jD_Ganancia;
    private javax.swing.JDialog jD_Inventario;
    private javax.swing.JDialog jD_LogIn;
    private javax.swing.JDialog jD_Modificar_Producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTA_Factura;
    private javax.swing.JTextField jTF_Categoria;
    private javax.swing.JTextField jTF_Categoria1;
    private javax.swing.JTextField jTF_Descuento;
    private javax.swing.JTextField jTF_Descuento1;
    private javax.swing.JTextField jTF_Edad;
    private javax.swing.JTextField jTF_Ganancia;
    private javax.swing.JTextField jTF_Nombre;
    private javax.swing.JTextField jTF_Nombre_Producto;
    private javax.swing.JTextField jTF_Nombre_Producto1;
    private javax.swing.JTextField jTF_Password;
    private javax.swing.JTextField jTF_Precio;
    private javax.swing.JTextField jTF_Precio1;
    private javax.swing.JTextField jTF_User;
    private javax.swing.JTable jT_Inventario;
    private javax.swing.JTable jT_Inventario1;
    // End of variables declaration//GEN-END:variables
    private String user = "usuario";
    private String pass = "12345hola";
    private double ganancias = 0;
    private double total_precio = 0;
    private double descuento = 0;
}
